from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class InstrumentProfile:
    ticker: str
    name: str
    asset_type: str
    exchange: str = ""
    sector: str = ""
    industry: str = ""
    description: str = ""
    aliases: tuple[str, ...] = ()

    @property
    def identity(self) -> str:
        listing = f" listed on {self.exchange}" if self.exchange else ""
        sector = f" {self.sector}" if self.sector else ""
        industry = f" in {self.industry}" if self.industry else ""
        return f"{self.ticker} is {self.name}, a {sector} {self.asset_type}{industry}{listing}.".replace(
            "  ", " "
        )


INSTRUMENT_PROFILES: dict[str, InstrumentProfile] = {
    "AAPL": InstrumentProfile(
        "AAPL",
        "Apple Inc.",
        "stock",
        "Nasdaq",
        "technology",
        "consumer electronics and services",
        "Apple sells iPhone, Mac, iPad, wearables, and services, and is one of the largest mega-cap technology weights in broad equity indexes.",
        ("Apple", "iPhone"),
    ),
    "AMD": InstrumentProfile(
        "AMD",
        "Advanced Micro Devices, Inc.",
        "stock",
        "Nasdaq",
        "technology",
        "semiconductors",
        "AMD designs CPUs, GPUs, and accelerator chips used across PCs, gaming, data centers, and AI infrastructure.",
        ("Advanced Micro Devices", "chip", "gpu"),
    ),
    "AMZN": InstrumentProfile(
        "AMZN",
        "Amazon.com, Inc.",
        "stock",
        "Nasdaq",
        "consumer discretionary",
        "online retail, cloud, advertising, and logistics",
        "Amazon combines e-commerce, AWS cloud infrastructure, advertising, media, and logistics exposure.",
        ("Amazon", "AWS", "cloud"),
    ),
    "ANET": InstrumentProfile(
        "ANET",
        "Arista Networks, Inc.",
        "stock",
        "NYSE",
        "technology",
        "cloud networking",
        "Arista sells high-speed networking hardware and software used in cloud and AI data-center buildouts.",
        ("Arista", "networking"),
    ),
    "APP": InstrumentProfile(
        "APP",
        "AppLovin Corporation",
        "stock",
        "Nasdaq",
        "technology",
        "advertising software",
        "AppLovin provides app monetization and advertising technology, with recent investor attention tied to AI-assisted ad targeting.",
        ("AppLovin", "ad tech"),
    ),
    "ARM": InstrumentProfile(
        "ARM",
        "Arm Holdings plc",
        "stock",
        "Nasdaq",
        "technology",
        "semiconductor intellectual property",
        "Arm licenses processor designs and chip architecture used across mobile, embedded, data-center, and AI hardware markets.",
        ("Arm Holdings", "semiconductor IP"),
    ),
    "ASML": InstrumentProfile(
        "ASML",
        "ASML Holding N.V.",
        "stock",
        "Nasdaq",
        "technology",
        "semiconductor equipment",
        "ASML supplies lithography systems used by advanced semiconductor manufacturers.",
        ("lithography", "semicap"),
    ),
    "AVGO": InstrumentProfile(
        "AVGO",
        "Broadcom Inc.",
        "stock",
        "Nasdaq",
        "technology",
        "semiconductors and infrastructure software",
        "Broadcom sells semiconductor connectivity products and enterprise infrastructure software, with AI networking exposure.",
        ("Broadcom", "AI networking"),
    ),
    "CEG": InstrumentProfile(
        "CEG",
        "Constellation Energy Corporation",
        "stock",
        "Nasdaq",
        "utilities",
        "nuclear and power generation",
        "Constellation is a large U.S. nuclear and power producer often watched as an AI data-center power-demand beneficiary.",
        ("Constellation", "nuclear", "power"),
    ),
    "CRWD": InstrumentProfile(
        "CRWD",
        "CrowdStrike Holdings, Inc.",
        "stock",
        "Nasdaq",
        "technology",
        "cybersecurity software",
        "CrowdStrike provides cloud-native cybersecurity software for endpoint, identity, and security operations use cases through its Falcon platform.",
        ("CrowdStrike", "cybersecurity", "Falcon"),
    ),
    "DDOG": InstrumentProfile(
        "DDOG",
        "Datadog, Inc.",
        "stock",
        "Nasdaq",
        "technology",
        "observability and cloud monitoring software",
        "Datadog provides infrastructure monitoring, logging, security monitoring, and observability tools for cloud software teams.",
        ("Datadog", "observability"),
    ),
    "DELL": InstrumentProfile(
        "DELL",
        "Dell Technologies Inc.",
        "stock",
        "NYSE",
        "technology",
        "hardware, servers, and infrastructure",
        "Dell sells PCs, servers, storage, and enterprise infrastructure, including AI server exposure.",
        ("Dell", "AI server"),
    ),
    "ETN": InstrumentProfile(
        "ETN",
        "Eaton Corporation plc",
        "stock",
        "NYSE",
        "industrials",
        "electrical equipment",
        "Eaton sells electrical and power-management equipment used in industrial, utility, and data-center infrastructure.",
        ("Eaton", "power equipment"),
    ),
    "GEV": InstrumentProfile(
        "GEV",
        "GE Vernova Inc.",
        "stock",
        "NYSE",
        "industrials",
        "power generation and grid equipment",
        "GE Vernova supplies power, wind, electrification, and grid equipment tied to energy infrastructure demand.",
        ("GE Vernova", "grid", "power"),
    ),
    "GOOG": InstrumentProfile(
        "GOOG",
        "Alphabet Inc. Class C",
        "stock",
        "Nasdaq",
        "communication services",
        "search, advertising, cloud, and AI",
        "Alphabet owns Google Search, YouTube, Google Cloud, Android, and AI research and product platforms.",
        ("Alphabet", "Google", "YouTube"),
    ),
    "GOOGL": InstrumentProfile(
        "GOOGL",
        "Alphabet Inc. Class A",
        "stock",
        "Nasdaq",
        "communication services",
        "search, advertising, cloud, and AI",
        "Alphabet owns Google Search, YouTube, Google Cloud, Android, and AI research and product platforms.",
        ("Alphabet", "Google", "YouTube"),
    ),
    "META": InstrumentProfile(
        "META",
        "Meta Platforms, Inc.",
        "stock",
        "Nasdaq",
        "communication services",
        "social platforms, advertising, and AI infrastructure",
        "Meta owns Facebook, Instagram, WhatsApp, Threads, and Reality Labs, with heavy AI infrastructure and ad-ranking exposure.",
        ("Facebook", "Instagram", "Meta"),
    ),
    "MRVL": InstrumentProfile(
        "MRVL",
        "Marvell Technology, Inc.",
        "stock",
        "Nasdaq",
        "technology",
        "semiconductors",
        "Marvell sells data-center, networking, storage, and custom silicon products with AI infrastructure exposure.",
        ("Marvell", "custom silicon"),
    ),
    "MSFT": InstrumentProfile(
        "MSFT",
        "Microsoft Corporation",
        "stock",
        "Nasdaq",
        "technology",
        "software, cloud, productivity, gaming, and AI",
        "Microsoft owns Azure, Office, Windows, GitHub, LinkedIn, Xbox, and Copilot/OpenAI-linked AI product exposure.",
        ("Microsoft", "Azure", "Copilot", "OpenAI"),
    ),
    "MU": InstrumentProfile(
        "MU",
        "Micron Technology, Inc.",
        "stock",
        "Nasdaq",
        "technology",
        "memory semiconductors",
        "Micron produces DRAM and NAND memory, including high-bandwidth memory used in AI accelerators.",
        ("Micron", "memory", "HBM"),
    ),
    "NET": InstrumentProfile(
        "NET",
        "Cloudflare, Inc.",
        "stock",
        "NYSE",
        "technology",
        "edge network, security, and developer infrastructure",
        "Cloudflare provides content delivery, network security, zero-trust, developer, and edge compute services.",
        ("Cloudflare", "edge", "security"),
    ),
    "NVDA": InstrumentProfile(
        "NVDA",
        "NVIDIA Corporation",
        "stock",
        "Nasdaq",
        "technology",
        "GPUs, accelerators, networking, and AI platforms",
        "NVIDIA designs GPUs, AI accelerators, networking systems, and software platforms for gaming, data centers, and AI workloads.",
        ("NVIDIA", "GPU", "AI accelerator"),
    ),
    "ORCL": InstrumentProfile(
        "ORCL",
        "Oracle Corporation",
        "stock",
        "NYSE",
        "technology",
        "database, enterprise software, and cloud infrastructure",
        "Oracle sells database, enterprise software, and cloud infrastructure services.",
        ("Oracle", "database"),
    ),
    "PLTR": InstrumentProfile(
        "PLTR",
        "Palantir Technologies Inc.",
        "stock",
        "Nasdaq",
        "technology",
        "data analytics and AI software",
        "Palantir provides data integration, analytics, and AI operations software for government and commercial customers.",
        ("Palantir", "AIP"),
    ),
    "PWR": InstrumentProfile(
        "PWR",
        "Quanta Services, Inc.",
        "stock",
        "NYSE",
        "industrials",
        "utility and energy infrastructure services",
        "Quanta builds and maintains electric grid, utility, renewable, pipeline, and communications infrastructure.",
        ("Quanta", "grid", "utility infrastructure"),
    ),
    "SMCI": InstrumentProfile(
        "SMCI",
        "Super Micro Computer, Inc.",
        "stock",
        "Nasdaq",
        "technology",
        "server hardware",
        "Super Micro Computer sells server and storage systems, including AI server platforms.",
        ("Supermicro", "AI server"),
    ),
    "SNOW": InstrumentProfile(
        "SNOW",
        "Snowflake Inc.",
        "stock",
        "NYSE",
        "technology",
        "cloud data platform software",
        "Snowflake provides a cloud data platform for data warehousing, analytics, sharing, and AI/data application workloads.",
        ("Snowflake", "cloud data", "data warehouse"),
    ),
    "TSLA": InstrumentProfile(
        "TSLA",
        "Tesla, Inc.",
        "stock",
        "Nasdaq",
        "consumer discretionary",
        "electric vehicles, energy storage, autonomy, and robotics",
        "Tesla sells electric vehicles, energy generation and storage products, and develops autonomy and robotics systems.",
        ("Tesla", "EV", "autonomy"),
    ),
    "TSM": InstrumentProfile(
        "TSM",
        "Taiwan Semiconductor Manufacturing Company Limited",
        "stock",
        "NYSE",
        "technology",
        "semiconductor foundry",
        "TSMC manufactures chips for fabless semiconductor companies and is a critical supplier to advanced AI and compute hardware.",
        ("TSMC", "foundry"),
    ),
    "VRT": InstrumentProfile(
        "VRT",
        "Vertiv Holdings Co",
        "stock",
        "NYSE",
        "industrials",
        "data-center power and cooling infrastructure",
        "Vertiv sells power, thermal management, and infrastructure systems for data centers and communications networks.",
        ("Vertiv", "data-center cooling"),
    ),
}


ETF_PROFILES: dict[str, InstrumentProfile] = {
    "ACWX": InstrumentProfile("ACWX", "iShares MSCI ACWI ex U.S. ETF", "ETF", "Nasdaq", "international equity", "global ex-U.S. stocks", "ACWX tracks developed and emerging-market equities outside the United States.", ("ex-US", "international")),
    "AGG": InstrumentProfile("AGG", "iShares Core U.S. Aggregate Bond ETF", "ETF", "NYSE Arca", "fixed income", "investment-grade U.S. bonds", "AGG tracks a broad U.S. investment-grade bond index.", ("aggregate bond", "bonds")),
    "ARKK": InstrumentProfile("ARKK", "ARK Innovation ETF", "ETF", "NYSE Arca", "thematic growth", "disruptive innovation stocks", "ARKK is an actively managed ETF focused on high-growth innovation themes.", ("ARK Innovation", "speculative growth")),
    "BIL": InstrumentProfile("BIL", "SPDR Bloomberg 1-3 Month T-Bill ETF", "ETF", "NYSE Arca", "cash-like fixed income", "short U.S. Treasury bills", "BIL holds short-duration U.S. Treasury bills and is trade-bot's main defensive cash-like proxy.", ("cash", "t-bill")),
    "BILS": InstrumentProfile("BILS", "SPDR Bloomberg 3-12 Month T-Bill ETF", "ETF", "NYSE Arca", "cash-like fixed income", "Treasury bills", "BILS holds Treasury bills with slightly longer maturities than BIL.", ("t-bill",)),
    "BIZD": InstrumentProfile("BIZD", "VanEck BDC Income ETF", "ETF", "NYSE Arca", "credit", "business development companies", "BIZD tracks publicly traded business development companies and private-credit-sensitive income exposure.", ("BDC", "private credit")),
    "BKLN": InstrumentProfile("BKLN", "Invesco Senior Loan ETF", "ETF", "NYSE Arca", "credit", "senior loans", "BKLN tracks floating-rate senior loans and is used as a leveraged-credit proxy.", ("bank loans", "senior loans")),
    "BOTZ": InstrumentProfile("BOTZ", "Global X Robotics & Artificial Intelligence ETF", "ETF", "Nasdaq", "thematic equity", "robotics and AI stocks", "BOTZ tracks robotics, automation, and AI-linked companies.", ("robotics", "AI ETF")),
    "BSV": InstrumentProfile("BSV", "Vanguard Short-Term Bond ETF", "ETF", "NYSE Arca", "fixed income", "short-term bonds", "BSV tracks short-term investment-grade bonds.", ("short bonds",)),
    "CLOU": InstrumentProfile("CLOU", "Global X Cloud Computing ETF", "ETF", "Nasdaq", "technology", "cloud software and infrastructure", "CLOU tracks cloud computing and software companies.", ("cloud ETF",)),
    "COWZ": InstrumentProfile("COWZ", "Pacer U.S. Cash Cows 100 ETF", "ETF", "Cboe", "equity factor", "free-cash-flow stocks", "COWZ tracks U.S. companies screened for high free-cash-flow yield.", ("cash flow", "value quality")),
    "DBA": InstrumentProfile("DBA", "Invesco DB Agriculture Fund", "ETF", "NYSE Arca", "commodities", "agricultural futures", "DBA provides futures-based agricultural commodity exposure.", ("agriculture",)),
    "DBC": InstrumentProfile("DBC", "Invesco DB Commodity Index Tracking Fund", "ETF", "NYSE Arca", "commodities", "broad commodity futures", "DBC tracks a basket of commodity futures.", ("commodities",)),
    "DIA": InstrumentProfile("DIA", "SPDR Dow Jones Industrial Average ETF Trust", "ETF", "NYSE Arca", "U.S. equity", "Dow Jones Industrial Average stocks", "DIA tracks the price-weighted Dow Jones Industrial Average.", ("Dow", "industrials benchmark")),
    "EEM": InstrumentProfile("EEM", "iShares MSCI Emerging Markets ETF", "ETF", "NYSE Arca", "international equity", "emerging-market stocks", "EEM tracks large and mid-cap emerging-market equities.", ("emerging markets",)),
    "EFA": InstrumentProfile("EFA", "iShares MSCI EAFE ETF", "ETF", "NYSE Arca", "international equity", "developed ex-U.S. stocks", "EFA tracks developed-market equities outside the U.S. and Canada.", ("EAFE", "developed ex-US")),
    "EWJ": InstrumentProfile("EWJ", "iShares MSCI Japan ETF", "ETF", "NYSE Arca", "international equity", "Japan stocks", "EWJ tracks Japanese equities.", ("Japan",)),
    "EWW": InstrumentProfile("EWW", "iShares MSCI Mexico ETF", "ETF", "NYSE Arca", "international equity", "Mexico stocks", "EWW tracks Mexican equities.", ("Mexico",)),
    "EWZ": InstrumentProfile("EWZ", "iShares MSCI Brazil ETF", "ETF", "NYSE Arca", "international equity", "Brazil stocks", "EWZ tracks Brazilian equities.", ("Brazil",)),
    "FBTC": InstrumentProfile("FBTC", "Fidelity Wise Origin Bitcoin Fund", "ETF", "Cboe", "crypto", "spot bitcoin", "FBTC is a spot bitcoin ETF.", ("Bitcoin", "BTC")),
    "GLD": InstrumentProfile("GLD", "SPDR Gold Shares", "ETF", "NYSE Arca", "commodities", "gold bullion", "GLD tracks gold bullion less fund expenses.", ("gold",)),
    "GLDM": InstrumentProfile("GLDM", "SPDR Gold MiniShares Trust", "ETF", "NYSE Arca", "commodities", "gold bullion", "GLDM is a lower-cost gold bullion ETF.", ("gold",)),
    "HYG": InstrumentProfile("HYG", "iShares iBoxx $ High Yield Corporate Bond ETF", "ETF", "NYSE Arca", "credit", "high-yield corporate bonds", "HYG tracks U.S. high-yield corporate bonds and is a credit-risk proxy.", ("junk bonds", "credit")),
    "IAU": InstrumentProfile("IAU", "iShares Gold Trust", "ETF", "NYSE Arca", "commodities", "gold bullion", "IAU tracks gold bullion less trust expenses.", ("gold",)),
    "IBIT": InstrumentProfile("IBIT", "iShares Bitcoin Trust ETF", "ETF", "Nasdaq", "crypto", "spot bitcoin", "IBIT is a spot bitcoin ETF.", ("Bitcoin", "BTC")),
    "IEF": InstrumentProfile("IEF", "iShares 7-10 Year Treasury Bond ETF", "ETF", "Nasdaq", "fixed income", "intermediate Treasury bonds", "IEF tracks 7-10 year U.S. Treasury bonds.", ("Treasuries", "duration")),
    "IGV": InstrumentProfile("IGV", "iShares Expanded Tech-Software Sector ETF", "ETF", "Cboe", "technology", "software stocks", "IGV tracks North American software companies.", ("software ETF",)),
    "IWM": InstrumentProfile("IWM", "iShares Russell 2000 ETF", "ETF", "NYSE Arca", "U.S. equity", "small-cap stocks", "IWM tracks the Russell 2000 small-cap index.", ("small caps",)),
    "LQD": InstrumentProfile("LQD", "iShares iBoxx $ Investment Grade Corporate Bond ETF", "ETF", "NYSE Arca", "credit", "investment-grade corporate bonds", "LQD tracks investment-grade U.S. corporate bonds.", ("credit", "corporate bonds")),
    "MCHI": InstrumentProfile("MCHI", "iShares MSCI China ETF", "ETF", "Nasdaq", "international equity", "China stocks", "MCHI tracks Chinese equities.", ("China",)),
    "MDY": InstrumentProfile("MDY", "SPDR S&P MidCap 400 ETF Trust", "ETF", "NYSE Arca", "U.S. equity", "mid-cap stocks", "MDY tracks the S&P MidCap 400.", ("mid caps",)),
    "MOAT": InstrumentProfile("MOAT", "VanEck Morningstar Wide Moat ETF", "ETF", "Cboe", "equity factor", "wide-moat U.S. stocks", "MOAT tracks U.S. companies Morningstar views as having sustainable competitive advantages.", ("wide moat", "quality")),
    "MTUM": InstrumentProfile("MTUM", "iShares MSCI USA Momentum Factor ETF", "ETF", "Cboe", "equity factor", "U.S. momentum stocks", "MTUM tracks U.S. stocks with positive momentum characteristics.", ("momentum",)),
    "QQQ": InstrumentProfile("QQQ", "Invesco QQQ Trust", "ETF", "Nasdaq", "U.S. equity", "Nasdaq-100 stocks", "QQQ tracks the Nasdaq-100 and is trade-bot's main growth and AI-beta benchmark.", ("Nasdaq 100", "growth benchmark")),
    "QQQM": InstrumentProfile("QQQM", "Invesco NASDAQ 100 ETF", "ETF", "Nasdaq", "U.S. equity", "Nasdaq-100 stocks", "QQQM is a lower-expense Nasdaq-100 ETF used similarly to QQQ.", ("Nasdaq 100",)),
    "QUAL": InstrumentProfile("QUAL", "iShares MSCI USA Quality Factor ETF", "ETF", "Cboe", "equity factor", "quality U.S. stocks", "QUAL tracks profitable, stable, quality-factor U.S. equities.", ("quality",)),
    "RSP": InstrumentProfile("RSP", "Invesco S&P 500 Equal Weight ETF", "ETF", "NYSE Arca", "U.S. equity", "equal-weight S&P 500 stocks", "RSP tracks the S&P 500 with equal weights, reducing mega-cap concentration versus SPY.", ("equal weight", "breadth")),
    "SCHD": InstrumentProfile("SCHD", "Schwab U.S. Dividend Equity ETF", "ETF", "NYSE Arca", "equity income", "dividend quality stocks", "SCHD tracks U.S. dividend-paying stocks screened for quality and sustainability.", ("dividend", "income")),
    "SGOV": InstrumentProfile("SGOV", "iShares 0-3 Month Treasury Bond ETF", "ETF", "NYSE Arca", "cash-like fixed income", "short Treasury bills", "SGOV tracks very short-duration U.S. Treasury bills.", ("cash", "t-bill")),
    "SHY": InstrumentProfile("SHY", "iShares 1-3 Year Treasury Bond ETF", "ETF", "Nasdaq", "fixed income", "short Treasury bonds", "SHY tracks 1-3 year U.S. Treasury bonds.", ("Treasuries",)),
    "SMH": InstrumentProfile("SMH", "VanEck Semiconductor ETF", "ETF", "Nasdaq", "technology", "semiconductor stocks", "SMH tracks a concentrated basket of semiconductor companies.", ("semiconductor ETF", "chips")),
    "SOXX": InstrumentProfile("SOXX", "iShares Semiconductor ETF", "ETF", "Nasdaq", "technology", "semiconductor stocks", "SOXX tracks U.S.-listed semiconductor companies.", ("semiconductor ETF", "chips")),
    "SPHB": InstrumentProfile("SPHB", "Invesco S&P 500 High Beta ETF", "ETF", "NYSE Arca", "equity factor", "high-beta S&P 500 stocks", "SPHB tracks high-beta S&P 500 constituents.", ("high beta",)),
    "SPY": InstrumentProfile("SPY", "SPDR S&P 500 ETF Trust", "ETF", "NYSE Arca", "U.S. equity", "S&P 500 stocks", "SPY tracks the S&P 500 and is trade-bot's broad U.S. equity benchmark.", ("S&P 500", "market beta")),
    "TLT": InstrumentProfile("TLT", "iShares 20+ Year Treasury Bond ETF", "ETF", "Nasdaq", "fixed income", "long Treasury bonds", "TLT tracks long-duration U.S. Treasury bonds and is sensitive to rate changes.", ("duration", "long bonds")),
    "UUP": InstrumentProfile("UUP", "Invesco DB U.S. Dollar Index Bullish Fund", "ETF", "NYSE Arca", "currency", "U.S. dollar futures", "UUP tracks a long U.S. dollar index futures strategy.", ("dollar", "DXY")),
    "USFR": InstrumentProfile("USFR", "WisdomTree Floating Rate Treasury Fund", "ETF", "NYSE Arca", "cash-like fixed income", "floating-rate Treasury notes", "USFR tracks floating-rate U.S. Treasury notes.", ("cash", "floating rate")),
    "USMV": InstrumentProfile("USMV", "iShares MSCI USA Min Vol Factor ETF", "ETF", "Cboe", "equity factor", "minimum-volatility U.S. stocks", "USMV tracks lower-volatility U.S. equities.", ("minimum volatility", "defensive equity")),
    "VEA": InstrumentProfile("VEA", "Vanguard FTSE Developed Markets ETF", "ETF", "NYSE Arca", "international equity", "developed ex-U.S. stocks", "VEA tracks developed-market equities outside the United States.", ("developed ex-US", "international")),
    "VIXY": InstrumentProfile("VIXY", "ProShares VIX Short-Term Futures ETF", "ETF", "NYSE Arca", "volatility", "short-term VIX futures", "VIXY tracks short-term VIX futures and is a volatility stress proxy.", ("VIX", "volatility")),
    "VOO": InstrumentProfile("VOO", "Vanguard S&P 500 ETF", "ETF", "NYSE Arca", "U.S. equity", "S&P 500 stocks", "VOO tracks the S&P 500.", ("S&P 500",)),
    "VT": InstrumentProfile("VT", "Vanguard Total World Stock ETF", "ETF", "NYSE Arca", "global equity", "global stocks", "VT tracks global developed and emerging-market equities.", ("global equity",)),
    "VTI": InstrumentProfile("VTI", "Vanguard Total Stock Market ETF", "ETF", "NYSE Arca", "U.S. equity", "total U.S. stock market", "VTI tracks the broad U.S. equity market.", ("total market",)),
    "VTV": InstrumentProfile("VTV", "Vanguard Value ETF", "ETF", "NYSE Arca", "equity factor", "large-cap value stocks", "VTV tracks large-cap U.S. value stocks.", ("value",)),
    "VWO": InstrumentProfile("VWO", "Vanguard FTSE Emerging Markets ETF", "ETF", "NYSE Arca", "international equity", "emerging-market stocks", "VWO tracks emerging-market equities.", ("emerging markets",)),
    "XLK": InstrumentProfile("XLK", "Technology Select Sector SPDR Fund", "ETF", "NYSE Arca", "sector equity", "S&P 500 technology stocks", "XLK tracks the S&P 500 technology sector.", ("technology sector",)),
    "XLE": InstrumentProfile("XLE", "Energy Select Sector SPDR Fund", "ETF", "NYSE Arca", "sector equity", "S&P 500 energy stocks", "XLE tracks the S&P 500 energy sector.", ("energy sector",)),
    "XLF": InstrumentProfile("XLF", "Financial Select Sector SPDR Fund", "ETF", "NYSE Arca", "sector equity", "S&P 500 financial stocks", "XLF tracks the S&P 500 financial sector.", ("financial sector",)),
    "XLI": InstrumentProfile("XLI", "Industrial Select Sector SPDR Fund", "ETF", "NYSE Arca", "sector equity", "S&P 500 industrial stocks", "XLI tracks the S&P 500 industrial sector.", ("industrial sector",)),
    "XLU": InstrumentProfile("XLU", "Utilities Select Sector SPDR Fund", "ETF", "NYSE Arca", "sector equity", "S&P 500 utilities stocks", "XLU tracks the S&P 500 utilities sector.", ("utilities",)),
    "XLV": InstrumentProfile("XLV", "Health Care Select Sector SPDR Fund", "ETF", "NYSE Arca", "sector equity", "S&P 500 health care stocks", "XLV tracks the S&P 500 health care sector.", ("health care",)),
}

INSTRUMENT_PROFILES.update(ETF_PROFILES)


def instrument_profile(ticker: str) -> InstrumentProfile | None:
    return INSTRUMENT_PROFILES.get(ticker.strip().upper())
