from __future__ import annotations

import re
from dataclasses import dataclass

import pandas as pd


@dataclass(frozen=True)
class MetricExplainer:
    metric: str
    category: str
    plain_english: str
    calculation: str
    how_to_read: str
    caution: str
    aliases: tuple[str, ...] = ()


METRIC_EXPLAINERS: tuple[MetricExplainer, ...] = (
    MetricExplainer(
        metric="CAGR",
        category="Performance",
        plain_english="Compounded annual growth rate: the annual return that would compound to the same ending value.",
        calculation="Ending equity divided by starting equity, annualized over the length of the test.",
        how_to_read="Higher is better, but only after checking drawdown, turnover, and robustness.",
        caution="A high CAGR can come from one lucky period or one concentrated theme.",
        aliases=("cagr", "median_cagr", "base_cagr", "overlay_cagr", "delta_cagr"),
    ),
    MetricExplainer(
        metric="Sharpe",
        category="Performance",
        plain_english="Return per unit of total volatility.",
        calculation="Average daily net return times 252 divided by annualized daily-return volatility.",
        how_to_read="Above 1 is useful for simple daily strategies; compare it across similar approaches.",
        caution="This implementation does not subtract a risk-free rate; Sharpe also penalizes upside volatility and can miss crash risk.",
        aliases=("sharpe", "median_sharpe", "base_sharpe", "overlay_sharpe", "delta_sharpe"),
    ),
    MetricExplainer(
        metric="Sortino",
        category="Performance",
        plain_english="Return per unit of downside volatility.",
        calculation="Average daily net return times 252 divided by annualized standard deviation of returns clipped at zero.",
        how_to_read="Useful when a strategy has upside jumps but controlled downside.",
        caution="It still depends on the historical sample and does not guarantee future tail control.",
        aliases=("sortino",),
    ),
    MetricExplainer(
        metric="Max Drawdown",
        category="Performance",
        plain_english="The worst peak-to-trough loss during the tested period.",
        calculation="Lowest percentage loss from a prior equity-curve high.",
        how_to_read="Less negative is better. This is the pain metric to compare against buy-and-hold.",
        caution="Future drawdowns can be worse than the historical maximum.",
        aliases=(
            "max_drawdown",
            "worst_drawdown",
            "current_drawdown",
            "base_max_drawdown",
            "overlay_max_drawdown",
            "best_max_drawdown",
        ),
    ),
    MetricExplainer(
        metric="Calmar",
        category="Performance",
        plain_english="Annual return divided by worst drawdown.",
        calculation="CAGR divided by absolute max drawdown.",
        how_to_read="Higher means more return per unit of drawdown pain.",
        caution="A high Calmar can be unstable when drawdown history is short.",
        aliases=("calmar", "median_calmar", "base_calmar", "overlay_calmar", "delta_calmar"),
    ),
    MetricExplainer(
        metric="Average Turnover",
        category="Trading",
        plain_english="How much of the portfolio changes on an average rebalance.",
        calculation="Average absolute change in portfolio weights.",
        how_to_read="Lower usually means fewer trades, less friction, and better account usability.",
        caution="Too-low turnover can also mean the system is slow to exit bad regimes.",
        aliases=("average_turnover", "delta_average_turnover"),
    ),
    MetricExplainer(
        metric="Time Underwater",
        category="Performance",
        plain_english=(
            "Share of evaluated days where the equity curve is below its prior high-water mark."
        ),
        calculation="Mean of days where drawdown is below zero.",
        how_to_read=(
            "High values mean the strategy often spends time below a prior peak; this can happen even "
            "when the drawdowns are shallow."
        ),
        caution=(
            "This is not the same as time spent in a severe drawdown. A strategy can have high time "
            "underwater and still have acceptable max drawdown."
        ),
        aliases=("Days below prior peak", "time_underwater", "underwater_rate"),
    ),
    MetricExplainer(
        metric="Ulcer Index",
        category="Performance",
        plain_english=(
            "Drawdown pain metric that combines depth and persistence of drawdowns."
        ),
        calculation="Square root of the average squared drawdown from prior equity highs.",
        how_to_read=(
            "Lower is better. Tiny below-peak days barely move it; deep and persistent drawdowns move it a lot."
        ),
        caution=(
            "It is still historical and sample-dependent, but it is usually more useful than raw days below peak."
        ),
        aliases=("ulcer_index", "pain_index"),
    ),
    MetricExplainer(
        metric="Variance Contribution",
        category="Attribution",
        plain_english="How much each proxy factor contributes to strategy return variance.",
        calculation="Covariance of the fitted factor return contribution with strategy returns, divided by strategy-return variance.",
        how_to_read=(
            "Positive values mean the factor explains strategy variance in the same direction; negative values "
            "mean it offsets strategy variance."
        ),
        caution=(
            "This can look similar to return contribution when the same factors both earned returns and drove volatility."
        ),
        aliases=("risk_contribution_pct", "variance_contribution", "risk contribution"),
    ),
    MetricExplainer(
        metric="Beta-Adjusted S&P Delta",
        category="Risk",
        plain_english=(
            "Approximate S&P 500-equivalent exposure after accounting for each holding's rolling beta."
        ),
        calculation="Sum of position weight times rolling beta to SPY over the configured lookback.",
        how_to_read="A 65% reading means the book behaves roughly like a 65% SPY allocation for broad-market moves.",
        caution="Rolling beta can change quickly in stress regimes and is only a linear approximation.",
        aliases=("beta_adjusted_spy_delta",),
    ),
    MetricExplainer(
        metric="Percent of Max Sleeve",
        category="Risk",
        plain_english="How much of a configured sleeve limit is currently being used.",
        calculation="Current sleeve weight divided by that sleeve's configured maximum exposure.",
        how_to_read="A 100% reading means the sleeve is at its current operating maximum.",
        caution="Sleeve limits are policy constraints, not proof that the exposure is attractive.",
        aliases=(
            "percent_of_max_sleeve",
            "stocks_percent_of_max_sleeve",
            "defensive_percent_of_max_sleeve",
            "gold_percent_of_max_sleeve",
            "crypto_percent_of_max_sleeve",
            "credit_percent_of_max_sleeve",
        ),
    ),
    MetricExplainer(
        metric="Factor R2",
        category="Attribution",
        plain_english="Share of the strategy's daily return variance explained by the proxy factor model.",
        calculation="1 minus residual variance divided by strategy-return variance.",
        how_to_read="High values mean the strategy is mostly explained by broad proxy factors; low values mean more residual strategy-specific behavior.",
        caution="A high R2 is not bad by itself, but it can reveal that several strategies are the same disguised factor bet.",
        aliases=("factor_model_r_squared", "factor_r2"),
    ),
    MetricExplainer(
        metric="Residual Share",
        category="Attribution",
        plain_english="Portion of absolute return contribution not explained by the proxy factor set.",
        calculation="Absolute residual strategy contribution divided by total absolute factor plus residual contribution.",
        how_to_read="Higher values suggest more unique behavior after broad beta, AI/growth, rates, credit, commodities, and volatility are considered.",
        caution="Residual behavior can be true skill, missing factors, noise, or overfit. Inspect robustness before trusting it.",
        aliases=("residual_contribution_share", "residual_share"),
    ),
    MetricExplainer(
        metric="Factor Decay",
        category="Attribution",
        plain_english="Whether recent factor exposure no longer resembles the full-history factor profile.",
        calculation="Compares recent beta, R2, and residual volatility against full-history attribution.",
        how_to_read="A flag means the strategy may be drifting, crowded, broken, or entering a new regime.",
        caution="Short windows can produce false alarms. Treat decay flags as review triggers, not automatic exits.",
        aliases=("drift_flag", "model_decay_flag", "beta_drift", "abs_beta_drift"),
    ),
    MetricExplainer(
        metric="Growth of $1",
        category="Performance",
        plain_english="Window-rebased equity curve showing how one dollar would have grown in the selected period.",
        calculation="Each selected strategy is divided by its value at the window start.",
        how_to_read="Use it to compare recent windows without the long-history chart dominating the view.",
        caution="Short windows are diagnostic, not proof that a strategy is structurally better.",
        aliases=("growth_of_1", "growth_of_$1", "windowed_performance"),
    ),
    MetricExplainer(
        metric="Worst 1Y/3Y/5Y CAGR",
        category="Robustness",
        plain_english="The worst rolling-window annual return for that horizon.",
        calculation="Calculate rolling 1, 3, or 5 year windows and report the weakest CAGR.",
        how_to_read="This tells you how bad the strategy looked when started at unlucky times.",
        caution="It still depends on the historical regimes available in the data.",
        aliases=("worst_1y_cagr", "worst_3y_cagr", "worst_5y_cagr", "worst_cagr"),
    ),
    MetricExplainer(
        metric="Positive Window Rate",
        category="Robustness",
        plain_english="Share of rolling windows with a positive return.",
        calculation="Count positive rolling windows divided by all tested rolling windows.",
        how_to_read="Higher means the strategy worked across more starting dates.",
        caution="A strategy can have many small wins and a few unacceptable losses.",
        aliases=("positive_window_rate", "delta_positive_1y_window_rate"),
    ),
    MetricExplainer(
        metric="Walk-Forward Median CAGR",
        category="Robustness",
        plain_english="Median return in sequential holdout windows after an initial burn-in span.",
        calculation="Evaluate the fixed strategy in repeated test windows and take the median holdout CAGR.",
        how_to_read="Better regime-breadth evidence than a single full-history backtest.",
        caution="Current folds do not retrain or re-optimize parameters, so this is a walk-forward holdout diagnostic rather than a full model-selection engine.",
        aliases=("walk_forward_median_cagr",),
    ),
    MetricExplainer(
        metric="Walk-Forward Worst CAGR",
        category="Robustness",
        plain_english="Worst annualized return across walk-forward holdout folds.",
        calculation="Minimum CAGR among all sequential holdout test windows.",
        how_to_read="This is a forward-style failure-mode metric.",
        caution="Annualizing short holdouts can make losses look larger or smaller than the lived path; folds do not refit strategy parameters.",
        aliases=("walk_forward_worst_cagr",),
    ),
    MetricExplainer(
        metric="Walk-Forward Positive Rate",
        category="Robustness",
        plain_english="Share of walk-forward holdout folds with positive returns.",
        calculation="Positive holdout folds divided by all holdout folds.",
        how_to_read="Higher means the approach held up across more unseen test periods.",
        caution="It does not say how large the losing folds were, and it does not prove future adaptability.",
        aliases=("walk_forward_positive_rate",),
    ),
    MetricExplainer(
        metric="Promotion Decision",
        category="Research",
        plain_english="Research triage label for whether an experiment deserves more attention.",
        calculation="Rule-based classification from promotion score, robustness, drawdown, and fragility checks.",
        how_to_read="Promote means monitor and paper test; it is not live-trading approval.",
        caution="A promoted candidate can still be rejected later after forward testing.",
        aliases=("promotion_decision", "decision"),
    ),
    MetricExplainer(
        metric="Promotion Score",
        category="Research",
        plain_english="Composite experiment score used to rank candidates.",
        calculation="Weighted ranks of return, drawdown, Calmar, walk-forward strength, and regime behavior.",
        how_to_read="Useful for sorting experiments quickly before reading details.",
        caution="A composite score can hide the reason a strategy is fragile.",
        aliases=("promotion_score", "best_score", "median_score"),
    ),
    MetricExplainer(
        metric="Growth-Constrained Utility Score",
        category="Research",
        plain_english="Outcome score for accumulation accounts that value high terminal wealth while keeping drawdowns inside a survivable band.",
        calculation="Log-scaled 15-year wealth with contributions, adjusted for validation quality, soft/hard drawdown penalties, overfit risk, left-tail behavior, and churn.",
        how_to_read="Use it to find candidates where extra CAGR appears worth the additional drawdown burden.",
        caution="This is a research-selection score, not live trade approval; weak walk-forward or regime evidence can still disqualify a high-growth backtest.",
        aliases=("growth_constrained_utility_score", "outcome_utility", "growth_utility"),
    ),
    MetricExplainer(
        metric="Growth Utility Tier",
        category="Research",
        plain_english="Plain-language tier derived from growth-constrained utility and drawdown eligibility.",
        calculation="Rule-based label from utility score and the hard drawdown gate.",
        how_to_read="Champion and challenger tiers deserve paper-monitoring review before lower tiers.",
        caution="A tier can change when new experiments, benchmarks, or validation diagnostics are added.",
        aliases=("growth_utility_tier",),
    ),
    MetricExplainer(
        metric="15-Year Terminal Wealth With Contributions",
        category="Performance",
        plain_english=(
            "Projected account value after applying the strategy CAGR to the configured starting "
            "balance and scheduled contributions."
        ),
        calculation=(
            "Starting value compounded by CAGR for 15 years plus the configured annual contribution "
            "split across the configured cadence; the default is monthly period-end deposits."
        ),
        how_to_read="This is the practical retirement-accumulation outcome to compare across high-growth and lower-drawdown strategies.",
        caution="It assumes the historical CAGR repeats for planning math only; it is not a forecast.",
        aliases=(
            "15Y Wealth",
            "15 Year Wealth",
            "15-year wealth",
            "terminal_wealth_with_contributions_15y",
            "terminal_wealth_15y",
            "projected_wealth",
        ),
    ),
    MetricExplainer(
        metric="Outcome Planning Assumptions",
        category="Performance",
        plain_english="The account, contribution, horizon, and drawdown policy used by the Outcome Frontier.",
        calculation="Defaults come from src/trade_bot/DEFAULTS.py and are applied consistently to deterministic and simulated outcome views.",
        how_to_read="Use these settings to confirm the wealth math matches the real planning problem before comparing strategies.",
        caution="Changing assumptions changes the wealth ranking; rerun the refresh stack after changing defaults so stored scorecards stay aligned.",
        aliases=(
            "Starting Account",
            "Annual Contribution",
            "Horizon",
            "Soft / Hard DD",
            "Projection Mode",
            "planning_assumptions",
            "outcome_assumptions",
        ),
    ),
    MetricExplainer(
        metric="Bootstrap Wealth Range",
        category="Performance",
        plain_english="Sequence-aware wealth distribution from resampling the selected strategy's historical daily returns.",
        calculation=(
            "Block bootstrap daily returns for the configured horizon, add scheduled contributions "
            "using the configured cadence, and report terminal-wealth quantiles."
        ),
        how_to_read="P10 is a worse-but-plausible sampled path, median is the center sampled path, and P90 is a better sampled path.",
        caution="This is historical return-sequence resampling. Use the regime-conditioned simulation beside it when today's scenario map matters.",
        aliases=(
            "Bootstrap P10 Wealth",
            "Bootstrap Median",
            "Bootstrap P90 Wealth",
            "terminal_wealth_p10",
            "terminal_wealth_p50",
            "terminal_wealth_p90",
            "sequence-aware outcome simulation",
        ),
    ),
    MetricExplainer(
        metric="Bootstrap Simulated Drawdown",
        category="Performance",
        plain_english="Path-level drawdown pain from the historical block-bootstrap simulations.",
        calculation="For each sampled path, compute max drawdown and Ulcer Index; the dashboard shows median simulated values.",
        how_to_read="Use this to see whether the terminal-wealth result depends on paths that would be hard to sit through.",
        caution="The simulation only resamples history and can miss unseen future drawdowns or changed regime behavior.",
        aliases=(
            "Median Sim DD",
            "Median Sim Ulcer",
            "bootstrap_max_drawdown",
            "bootstrap_ulcer_index",
            "simulated_drawdown",
        ),
    ),
    MetricExplainer(
        metric="Regime-Conditioned Forward Simulation",
        category="Performance",
        plain_english=(
            "Forward planning simulation that blends current scenario probabilities with historical "
            "regime-labeled return paths."
        ),
        calculation=(
            "Label historical strategy returns into risk-off, transition, fragile risk-on, and risk-on "
            "regimes; blend today's scenario probabilities with empirical regime transitions; sample "
            "future paths with scheduled contributions."
        ),
        how_to_read=(
            "Use it to see whether current scenarios materially widen the wealth and drawdown range "
            "versus simple CAGR or bootstrap views."
        ),
        caution=(
            "This is still scenario-conditioned historical simulation, not an oracle. Sparse regimes "
            "and unseen future shocks can make realized outcomes worse."
        ),
        aliases=(
            "Projection Mode",
            "Forward P10 Wealth",
            "Forward Median",
            "Forward P90 Wealth",
            "terminal_wealth_forward_p10",
            "terminal_wealth_forward_p50",
            "terminal_wealth_forward_p90",
            "regime_forward_simulation",
        ),
    ),
    MetricExplainer(
        metric="Severe Drawdown Probability",
        category="Performance",
        plain_english="Share of forward simulation paths that breach the configured hard drawdown limit.",
        calculation="Count simulated paths with max drawdown at or below the hard drawdown limit, divided by all paths.",
        how_to_read="Lower is better. A non-zero value means the selected strategy still has paths that violate the pain budget.",
        caution="The hard drawdown limit is configurable and the probability is only as good as the historical regime library.",
        aliases=("Severe DD Prob", "severe_drawdown_probability", "hard_drawdown_breach_rate"),
    ),
    MetricExplainer(
        metric="Forward Simulated Drawdown",
        category="Performance",
        plain_english="Median max drawdown across the regime-conditioned forward simulation paths.",
        calculation=(
            "For each simulated path, compute the worst peak-to-trough loss; then report the "
            "median path's max drawdown."
        ),
        how_to_read="Less negative is better. Compare this with historical max drawdown and bootstrap drawdown.",
        caution=(
            "It is conditioned on the empirical regime library and today's scenario blend, so it can "
            "understate drawdowns from regimes not present in the historical sample."
        ),
        aliases=("Median Forward DD", "forward_median_drawdown", "max_drawdown_p50"),
    ),
    MetricExplainer(
        metric="Capital Shortfall Probability",
        category="Performance",
        plain_english=(
            "Share of simulated paths that finish below the sum of starting capital plus planned "
            "contributions."
        ),
        calculation=(
            "Count simulated terminal wealth values below starting balance plus total planned "
            "contributions, divided by all paths."
        ),
        how_to_read=(
            "This is a practical bad-outcome flag: it asks whether compounding failed to outrun "
            "the money put into the account."
        ),
        caution="It does not include inflation or taxes unless a separate taxable or real-return layer is used.",
        aliases=("Capital Shortfall Prob", "capital_impairment_probability", "capital_shortfall"),
    ),
    MetricExplainer(
        metric="Forward Regime Mix",
        category="Performance",
        plain_english="Average share of simulated path days spent in each broad regime.",
        calculation="For each path, count sampled days by regime; then summarize the regime shares across paths.",
        how_to_read="High risk-off or transition shares mean the simulation is stress-testing more defensive or unstable futures.",
        caution="Regime labels are coarse and empirical; they are useful for diagnostics, not precise macro classification.",
        aliases=("mean_risk_off_share", "mean_transition_share", "Path Regime Share", "regime_mix"),
    ),
    MetricExplainer(
        metric="Extra Wealth Versus Benchmark",
        category="Performance",
        plain_english="Projected wealth difference versus a benchmark under the same 15-year contribution assumptions.",
        calculation="Selected strategy projected wealth minus benchmark projected wealth.",
        how_to_read="Positive means the selected strategy projects more wealth than the benchmark under the planning assumptions; negative means it trails.",
        caution="This is scenario math from historical CAGR, not a forecast. It can swing sharply when CAGR estimates are close.",
        aliases=("Extra vs SPY", "Extra vs QQQ", "extra_wealth_vs_spy", "extra_wealth_vs_qqq"),
    ),
    MetricExplainer(
        metric="Drawdown Recovery Return",
        category="Performance",
        plain_english="Gain required to recover from the reported max drawdown.",
        calculation="1 divided by 1 minus drawdown depth, minus 1. A 20 percent drawdown requires a 25 percent rebound.",
        how_to_read="Use it to translate drawdown into the recovery burden you would need to sit through.",
        caution="The time required to recover can matter more than the percentage recovery alone.",
        aliases=("Recovery Needed", "drawdown_recovery_return", "recovery_return_required"),
    ),
    MetricExplainer(
        metric="After-Tax CAGR",
        category="Tax",
        plain_english="Estimated CAGR after applying configured taxable-account rates to realized gains, losses, wash-sale adjustments, and loss carryforwards.",
        calculation="Taxable backtest equity after year-end estimated tax cash flows, then the standard CAGR formula.",
        how_to_read="Compare this with pre-tax CAGR to see whether active trading survives taxable-account drag.",
        caution="This is an estimate from configured assumptions and reconstructed lots; broker lots and real tax advice still govern live decisions.",
        aliases=("after_tax_cagr",),
    ),
    MetricExplainer(
        metric="Tax Drag",
        category="Tax",
        plain_english="Annualized return lost to estimated taxable-account effects.",
        calculation="Pre-tax CAGR minus after-tax CAGR, shown in basis points per year.",
        how_to_read="Lower is better when returns are comparable; high drag means turnover or short-term realizations are eating the edge.",
        caution="A strategy can have high tax drag and still be worth monitoring if the after-tax terminal wealth remains strong.",
        aliases=("tax_drag_bps_per_year", "tax_drag"),
    ),
    MetricExplainer(
        metric="Wash-Sale Disallowed Loss",
        category="Tax",
        plain_english="Estimated losses that cannot currently reduce taxable gains because a similar replacement position was bought inside the wash-sale window.",
        calculation="Losses on sold lots multiplied by replacement quantity inside the configured wash-sale window, capped at the realized loss.",
        how_to_read="Large values mean the strategy is trying to harvest losses but re-entering too quickly or too similarly.",
        caution="The model uses configured substitute maps and is intentionally conservative; actual wash-sale treatment needs tax review.",
        aliases=("wash_sale_disallowed_loss",),
    ),
    MetricExplainer(
        metric="After-Tax Growth-Constrained Utility Score",
        category="Tax",
        plain_english="Growth-constrained outcome score recomputed with estimated after-tax CAGR and drawdown.",
        calculation="Same utility formula as the pre-tax score, but using after-tax CAGR and after-tax max drawdown.",
        how_to_read="Use this when comparing strategies for a taxable brokerage account rather than an IRA-like account.",
        caution="Do not compare taxable and pre-tax scores without checking the account profile and tax model status.",
        aliases=("after_tax_growth_constrained_utility_score", "after_tax_growth_utility"),
    ),
    MetricExplainer(
        metric="Robustness Score",
        category="Research",
        plain_english="Composite score focused on stability across windows, walk-forward folds, and regimes.",
        calculation="Weighted ranks of rolling-window, walk-forward, and regime-resilience metrics.",
        how_to_read="Higher means less evidence of one-period overfitting.",
        caution="Robustness is historical breadth, not certainty.",
        aliases=("robustness_score",),
    ),
    MetricExplainer(
        metric="Role",
        category="Research",
        plain_english="How a strategy is intended to be used in the portfolio.",
        calculation="Manual experiment metadata: core, satellite, overlay, or operating-system candidate.",
        how_to_read="Core can carry more capital; satellite is opportunistic; overlay modifies sizing or risk.",
        caution="Role is a design label, not a guarantee of safety.",
        aliases=("role", "research_role"),
    ),
    MetricExplainer(
        metric="Left-Tail Regime Return",
        category="Regime Tests",
        plain_english="Performance during named stress or crisis windows.",
        calculation="Total return inside the historical windows tagged as left-tail regimes.",
        how_to_read="Less negative is better. This is directly tied to avoiding retirement-damaging drawdowns.",
        caution="Named regimes are sparse and may not match the next crisis.",
        aliases=("left_tail_regime_return", "left_tail_regime_cagr"),
    ),
    MetricExplainer(
        metric="Transition Regime Hit Rate",
        category="Regime Tests",
        plain_english="Share of market-transition windows where the strategy made money.",
        calculation="Positive transition-regime windows divided by all transition-regime windows.",
        how_to_read="Important for detecting whether the strategy survives leadership changes and policy whipsaw.",
        caution="A low value means the strategy may be late when market character changes.",
        aliases=("transition_regime_hit_rate", "transition_regime_return"),
    ),
    MetricExplainer(
        metric="Regime Positive Rate",
        category="Regime Tests",
        plain_english="Share of named regime windows with positive returns.",
        calculation="Positive named-regime windows divided by all named-regime windows.",
        how_to_read="Shows whether the strategy wins across varied market environments.",
        caution="A strategy can be good overall even with a mediocre regime hit rate if losses are controlled.",
        aliases=("regime_positive_rate",),
    ),
    MetricExplainer(
        metric="Risk Status",
        category="Current State",
        plain_english="Dashboard color/state summary of current market risk.",
        calculation="Derived from the price/ratio confirmation matrix plus SPY, QQQ, HYG, and VIXY stress checks.",
        how_to_read="Green allows normal risk, yellow asks for caution, red asks for capital preservation.",
        caution="Macro, event, scenario, and portfolio-risk layers affect the later trade-decision risk budget rather than this base risk-status color.",
        aliases=("risk_status", "risk"),
    ),
    MetricExplainer(
        metric="Risk Score",
        category="Current State",
        plain_english="Numerical estimate of current market risk pressure.",
        calculation="Weighted current-state signals scaled roughly from 0 to 1.",
        how_to_read="Higher means more evidence for reducing risk or requiring confirmation.",
        caution="Small changes are less important than direction, drivers, and threshold crossings.",
        aliases=("risk_score", "mean_risk_score"),
    ),
    MetricExplainer(
        metric="Regime Instability Score",
        category="Current State",
        plain_english="Watch-only estimate of whether market internals look statistically unstable.",
        calculation="Weighted blend of SPY +/-1% day share, realized volatility, cross-sectional dispersion, VIXY pressure, correlation shift, breadth/concentration, and credit stress.",
        how_to_read="Higher means the market may be in a transition regime even if headline trend has not broken.",
        caution="This is not currently allowed to change trade sizing; it needs ablation testing before becoming an allocation signal.",
        aliases=(
            "regime_instability_score",
            "regime_instability_state",
            "component_score",
            "spy_ytd_large_move_share",
        ),
    ),
    MetricExplainer(
        metric="Severity",
        category="Current State",
        plain_english="How urgent the dashboard thinks today's action review is.",
        calculation="Points from risk state, scenario risk, news pressure, trade size, and open tickets.",
        how_to_read="Use it to separate do-nothing days from small-action or critical-action days.",
        caution="High severity means review; it does not force execution.",
        aliases=("severity",),
    ),
    MetricExplainer(
        metric="Max Change",
        category="Trade Decision",
        plain_english="Largest target-weight change in the current recommendation.",
        calculation="Maximum absolute difference between current and target weights.",
        how_to_read="Large values mean the recommendation deserves extra human review.",
        caution="Large changes can be caused by stale positions, not just a new signal.",
        aliases=("max_change", "max_position_change", "delta_weight"),
    ),
    MetricExplainer(
        metric="Risk Budget",
        category="Trade Decision",
        plain_english="How much of normal strategy risk is currently allowed.",
        calculation="Minimum of risk-status, scenario, event, and validated-macro multipliers, then multiplied by any portfolio-risk multiplier.",
        how_to_read="1.00 means normal size; 0.50 means half-size; near 0 means mostly defensive.",
        caution="It controls sizing, not whether the underlying forecast is right.",
        aliases=(
            "risk_budget",
            "risk_budget_multiplier",
            "portfolio_risk_multiplier",
            "scenario_event_macro_multiplier",
        ),
    ),
    MetricExplainer(
        metric="Posture Calibration",
        category="Trade Decision",
        plain_english="Bias check for whether the recommendation may be too defensive given constructive scenario evidence.",
        calculation="Rule-based status from risk-off, risk-on, fragile-upside, transition, event pressure, macro pressure, and proposed risk reduction.",
        how_to_read="Use warnings as a prompt to review upside participation before accepting a de-risking trade.",
        caution="This is a governance check, not an override; it does not force the system to add risk.",
        aliases=(
            "posture_calibration_status",
            "posture_calibration_signal",
            "posture_calibration_note",
        ),
    ),
    MetricExplainer(
        metric="Opportunity Pressure",
        category="Trade Decision",
        plain_english="How much constructive medium-term evidence is pushing against defensive sizing.",
        calculation="risk_on + fragile_upside + 0.5 * transition - risk_off - event_pressure - macro_pressure, clipped from 0 to 1.",
        how_to_read="Higher values mean defensive recommendations deserve extra upside-participation review.",
        caution="It is not a forecast return and should be read with price, breadth, credit, and drawdown evidence.",
        aliases=(
            "opportunity_pressure",
            "one_month_risk_on_probability",
            "constructive_scenario_probability",
            "current_risk_asset_weight",
            "target_risk_asset_weight",
            "target_defensive_weight",
        ),
    ),
    MetricExplainer(
        metric="Launch Readiness",
        category="Launch Lab",
        plain_english="Entry-gate conclusion for whether to start or scale a strategy with new capital now.",
        calculation="Combines historical launch-window evidence, current strategy behavior, and current risk/scenario diagnostics.",
        how_to_read="Ready is strongest, Set means starter or staged sleeve, Wait means keep on deck, and No-go means do not launch from this setup.",
        caution="This is new-capital timing guidance. It does not replace Book Alignment for a paper or live sleeve that is already running.",
        aliases=(
            "Launch Gate",
            "launch readiness",
            "launch_gate",
            "launch_readiness",
            "launch_label",
            "launch_action",
            "launch_read",
            "current blockers",
            "why keep watching",
            "what to do instead",
            "current launch gate",
            "entry friction",
            "launch support",
            "next investigation",
            "context",
            "ready",
            "set",
            "wait",
            "no-go",
            "no go",
        ),
    ),
    MetricExplainer(
        metric="Launch Score",
        category="Launch Lab",
        plain_english="Composite score for how attractive the current setup is for starting or scaling a selected strategy.",
        calculation="Historical entry score adjusted by current launch diagnostics such as risk status, drawdown, risk-off probability, and confirmation shares.",
        how_to_read="Higher is better. Scores near one support launch; middling scores usually argue for a staged sleeve; low scores argue for waiting.",
        caution="The score summarizes evidence, but the component rows explain why the launch gate is open, staged, or closed.",
        aliases=("launch_score", "entry score", "launch gate score"),
    ),
    MetricExplainer(
        metric="Beat Rate",
        category="Launch Lab",
        plain_english="Share of sampled historical launch starts where the selected launch protocol beat the selected benchmark.",
        calculation="Count start windows where protocol return was greater than benchmark return, divided by all valid sampled start windows.",
        how_to_read="Higher means the entry protocol more often beat the benchmark from similar historical start dates.",
        caution="A high beat rate can still hide bad downside tails. Read it with bad-start rate, worst return, and max drawdown.",
        aliases=(
            "beat rate",
            "beat_rate",
            "beats_benchmark",
            "historical beat rate",
            "benchmark beat rate",
        ),
    ),
    MetricExplainer(
        metric="Bad-Start Rate",
        category="Launch Lab",
        plain_english="Share of sampled historical launch starts that produced a bad early outcome.",
        calculation="Count windows where total return was negative or first-month drawdown breached the configured bad-start threshold, divided by all valid start windows.",
        how_to_read="Lower is better. A high value means the strategy often punishes unlucky launch timing.",
        caution="This is launch-timing risk, not the full strategy max drawdown over its whole backtest.",
        aliases=(
            "bad start rate",
            "bad-start rate",
            "bad_start_rate",
            "bad_start",
            "bad launch",
            "bad start",
        ),
    ),
    MetricExplainer(
        metric="Positive-Start Rate",
        category="Launch Lab",
        plain_english="Share of sampled historical launch starts where the selected protocol made money over the launch horizon.",
        calculation="Count windows with protocol total return above zero, divided by all valid sampled start windows.",
        how_to_read="Higher means the strategy was less sensitive to unlucky start dates over the selected horizon.",
        caution="Positive does not mean better than benchmark. Pair it with beat rate and excess return.",
        aliases=(
            "positive start rate",
            "positive-start rate",
            "positive_start_rate",
            "positive return rate",
            "positive_return_rate",
            "positive_return",
        ),
    ),
    MetricExplainer(
        metric="Launch Protocol",
        category="Launch Lab",
        plain_english="The deployment schedule being tested for new capital.",
        calculation="Configured launch alternatives such as immediate full launch or 25 percent now with a 4, 8, or 12 week ramp.",
        how_to_read="Use this to compare whether immediate deployment or staged entry handles current market risk better.",
        caution="The best protocol can differ by strategy, benchmark, horizon, and current risk regime.",
        aliases=(
            "protocol",
            "recommended protocol",
            "protocol comparison",
            "protocol comparison for the primary horizon",
            "immediate full launch",
            "25% now / 4w ramp",
            "25% now / 8w ramp",
            "25% now / 12w ramp",
            "ramp_weeks",
        ),
    ),
    MetricExplainer(
        metric="Entry Backtest",
        category="Launch Lab",
        plain_english="Historical test of what happened when a strategy was adopted from many possible start dates.",
        calculation="Samples historical start dates, applies each launch protocol, and measures forward return, benchmark return, excess return, drawdown, and bad-start behavior.",
        how_to_read="Use this to see whether launching now resembles periods where the strategy often worked or often stumbled.",
        caution="The sampled starts come from available history; future launch conditions can be worse or different.",
        aliases=(
            "entry backtest",
            "launch start-date detail",
            "historical launch starts",
            "sampled start date",
            "start_date",
            "end_date",
            "historical pattern",
            "best start",
            "worst start",
            "total_return",
            "total return",
        ),
    ),
    MetricExplainer(
        metric="First-Month Drawdown",
        category="Launch Lab",
        plain_english="Worst drawdown during the first month after a sampled launch start.",
        calculation="For each sampled start window, compute the peak-to-trough drawdown during the first month of the launch path.",
        how_to_read="This is the early-regret metric: it estimates how painful the strategy can feel soon after starting.",
        caution="It does not measure later drawdowns after the first month.",
        aliases=(
            "first month drawdown",
            "first-month drawdown",
            "first_month_drawdown",
            "median_first_month_drawdown",
            "worst_first_month_drawdown",
        ),
    ),
    MetricExplainer(
        metric="Ramp Plan",
        category="Launch Lab",
        plain_english="Dollar schedule for staging new capital into a strategy.",
        calculation="Splits the configured launch sleeve across the selected protocol's ramp weeks and reports deployed capital and reserved cash.",
        how_to_read="Use it when Launch Lab says Set or Wait-but-starter-sleeve rather than immediate full launch.",
        caution="Re-check the launch gate before each staged tranche; stale conditions can invalidate the ramp.",
        aliases=(
            "ramp plan",
            "ramp_plan",
            "launch ramp dollars",
            "stage in",
            "staged ramp",
            "starter sleeve",
            "initial_ramp_fraction",
            "target_fraction_of_strategy",
            "account_fraction_deployed",
            "capital_deployed",
            "cash_reserved",
            "ramp read",
            "execution rule",
            "reserved cash",
            "ramp weeks",
            "week",
        ),
    ),
    MetricExplainer(
        metric="Final Sleeve Fraction",
        category="Launch Lab",
        plain_english="Final fraction of the intended strategy sleeve to deploy after the ramp completes.",
        calculation="User-selected final sleeve fraction multiplied by the configured test capital.",
        how_to_read="A smaller value makes Launch Lab test a starter sleeve rather than full strategy deployment.",
        caution="Changing this affects launch sizing, not the historical strategy backtest itself.",
        aliases=(
            "final sleeve fraction",
            "final_sleeve_fraction",
            "final sleeve",
            "final deployment",
            "target_fraction",
            "test sleeve",
        ),
    ),
    MetricExplainer(
        metric="Test Capital",
        category="Launch Lab",
        plain_english="Dollar amount being considered for a new paper, pseudo-live, live, or scale-up sleeve.",
        calculation="User-entered capital multiplied by the final sleeve fraction and any ramp schedule.",
        how_to_read="Use small amounts first when moving from research to live behavior.",
        caution="This is only a planning input until tickets or executions are logged in Forward Test.",
        aliases=("test capital", "launch capital", "new capital", "scale-up capital", "capital to launch"),
    ),
    MetricExplainer(
        metric="Launch Benchmark",
        category="Launch Lab",
        plain_english="Reference strategy used to judge whether a launch protocol added value.",
        calculation="Compares protocol return to the selected benchmark return over the same sampled launch windows.",
        how_to_read="Use SPY, QQQ, or another relevant benchmark to avoid mistaking a rising market for launch skill.",
        caution="A strategy can beat one benchmark while trailing another with higher risk or different exposure.",
        aliases=(
            "launch benchmark",
            "benchmark",
            "benchmark_return",
            "benchmark return",
            "median return",
            "worst return",
            "excess_return",
            "median_excess_return",
            "worst_excess_return",
        ),
    ),
    MetricExplainer(
        metric="Launching vs Operating",
        category="Launch Lab",
        plain_english="Distinction between deciding when to start new capital and managing a strategy that is already running.",
        calculation="Launch Lab uses entry timing and ramp evidence; operating controls use current target weights, Book Alignment, tickets, and Forward Test.",
        how_to_read="Use Launch Lab before starting or scaling; use Book Alignment and Forward Test after the sleeve is active.",
        caution="Do not let launch timing override the running book's daily alignment process.",
        aliases=(
            "launching vs operating",
            "launch behavior",
            "operating behavior",
            "scale-up behavior",
            "running book",
            "book alignment",
            "new capital",
            "scale-up capital",
            "mode",
            "question",
            "uses",
            "output",
            "what_not_to_do",
        ),
    ),
    MetricExplainer(
        metric="Current Launch Diagnostics",
        category="Launch Lab",
        plain_english="Current-state evidence used to adjust whether launch timing is favorable.",
        calculation="Reads strategy drawdown and recent returns, market risk status, scenario probabilities, and confirmation shares.",
        how_to_read="Use the diagnostics table to understand why the launch gate says Ready, Set, Wait, or No-go.",
        caution="Diagnostics can support staging without changing the strategy's actual daily target weights.",
        aliases=(
            "current launch diagnostics",
            "strategy_current_drawdown",
            "strategy_return_1m",
            "strategy_return_3m",
            "risk_off_1m_probability",
            "transition_1m_probability",
            "bullish_confirmation_share",
            "bearish_confirmation_share",
            "score_impact",
            "launch_friction",
            "stage_in_bias",
            "supports_launch",
        ),
    ),
    MetricExplainer(
        metric="1M Risk-Off Probability",
        category="Scenarios",
        plain_english="Scenario model probability assigned to one-month risk-off outcomes.",
        calculation="Sum of 1-month scenario probabilities whose bucket is risk-off.",
        how_to_read="Higher values should tighten position sizing and off-ramp rules.",
        caution="This is a model-implied probability, not an option-market probability.",
        aliases=("1m_risk_off", "one_month_risk_off_probability", "risk_off_probability"),
    ),
    MetricExplainer(
        metric="Scenario Probability",
        category="Scenarios",
        plain_english="Relative probability assigned to a future-state scenario.",
        calculation="Softmax-normalized score from scenario drivers such as trend, credit, breadth, and oil.",
        how_to_read="Use it to understand why the risk engine is sizing up or down.",
        caution="Scenario probabilities are directional rankings, not calibrated odds yet.",
        aliases=("probability",),
    ),
    MetricExplainer(
        metric="Risk Bucket",
        category="Scenarios",
        plain_english="Scenario grouping used by the risk engine.",
        calculation="Template metadata such as risk_on, transition, risk_off, or risk_on_fragile.",
        how_to_read="Risk-off and transition buckets reduce allowed risk more than constructive buckets.",
        caution="The bucket is only as good as the scenario drivers feeding it.",
        aliases=("risk_bucket",),
    ),
    MetricExplainer(
        metric="Event Pressure",
        category="News And Events",
        plain_english="How much current news/event risk is pressuring the risk budget.",
        calculation="Active event-risk items converted into a sizing multiplier input.",
        how_to_read="Higher values mean the system sees market-relevant event risk that needs confirmation.",
        caution="News can lead, lag, or be ignored by markets, so price confirmation matters.",
        aliases=("event_pressure",),
    ),
    MetricExplainer(
        metric="Urgency Score",
        category="News And Events",
        plain_english="How important and time-sensitive a news item appears to be.",
        calculation="Classification confidence, source priority, recency, category, and phase combined.",
        how_to_read="High urgency items can become active event-risk context.",
        caution="Urgency is not the same as trade direction.",
        aliases=("urgency_score",),
    ),
    MetricExplainer(
        metric="News Phase",
        category="News And Events",
        plain_english="Whether news is likely leading markets, confirming prices, or explaining past moves.",
        calculation="Text classification into leading_warning, coincident_confirmation, lagging_explanation, or uncertain.",
        how_to_read="Leading warnings should be watched before price confirms; lagging items carry less signal.",
        caution="Phase can be wrong when information is partially priced already.",
        aliases=("phase", "event_phase"),
    ),
    MetricExplainer(
        metric="Expected Shortfall 95",
        category="Risk Engine",
        plain_english="Average loss on days worse than the 95th percentile loss threshold.",
        calculation="Positive loss magnitude of the mean return at or below the 5th percentile in the tail window.",
        how_to_read="Lower is better. It is stricter than value-at-risk because it averages tail losses.",
        caution="It is backward-looking and can understate unseen crash behavior.",
        aliases=(
            "es_95",
            "expected_shortfall",
            "portfolio_expected_shortfall_95",
            "post_expected_shortfall_95",
            "pre_expected_shortfall_95",
            "max_expected_shortfall_95",
        ),
    ),
    MetricExplainer(
        metric="Max Stress Loss",
        category="Risk Engine",
        plain_english="Estimated portfolio loss under the worst configured stress scenario.",
        calculation="Apply configured group-level shock returns to current weights and report the largest positive loss magnitude.",
        how_to_read="Use it to see if the target portfolio violates drawdown guardrails before trading.",
        caution="Stress scenarios are incomplete by design; the next shock may be different.",
        aliases=("max_stress_loss", "post_max_stress_loss", "pre_max_stress_loss"),
    ),
    MetricExplainer(
        metric="Scenario-Weighted Stress Loss",
        category="Risk Engine",
        plain_english="Stress loss adjusted by current scenario probabilities.",
        calculation="Stress losses weighted by scenario-probability inputs and summed.",
        how_to_read="Useful when multiple future states are plausible and not all are equally likely.",
        caution="Bad probability calibration can make this too lenient or too strict.",
        aliases=(
            "scenario_weighted_stress_loss",
            "post_scenario_weighted_stress_loss",
            "pre_scenario_weighted_stress_loss",
            "max_scenario_weighted_stress_loss",
        ),
    ),
    MetricExplainer(
        metric="Equity Beta",
        category="Risk Engine",
        plain_english="Sensitivity of the portfolio to broad equity-market moves.",
        calculation="Regression-style exposure to the broad equity proxy, usually SPY.",
        how_to_read="1.00 behaves like full market beta; below 1 is less equity-sensitive.",
        caution="Beta can change quickly during crises when correlations rise.",
        aliases=("equity_beta", "portfolio_equity_beta", "post_equity_beta", "pre_equity_beta"),
    ),
    MetricExplainer(
        metric="AI Beta",
        category="Risk Engine",
        plain_english="Sensitivity to AI/semiconductor/mega-cap growth exposure.",
        calculation="Exposure to AI proxy assets such as SMH, SOXX, QQQ, and related names.",
        how_to_read="High AI beta is acceptable only when AI leadership and risk budget both confirm.",
        caution="This is the key concentration risk if AI capex or mega-cap leadership reprices.",
        aliases=("ai_beta", "portfolio_ai_beta", "post_ai_beta", "pre_ai_beta", "max_ai_beta"),
    ),
    MetricExplainer(
        metric="Correlation Shift",
        category="Risk Engine",
        plain_english="How much recent asset correlation differs from longer-term correlation.",
        calculation="Short-lookback average correlation minus long-lookback average correlation.",
        how_to_read="Positive shifts can mean diversification is failing when it is needed most.",
        caution="Correlation can spike after losses have already started.",
        aliases=(
            "correlation_shift",
            "average_correlation_short",
            "average_correlation_long",
            "correlation_regime_shift",
        ),
    ),
    MetricExplainer(
        metric="Marginal Risk Contribution",
        category="Risk Engine",
        plain_english="How much each holding contributes to total portfolio risk.",
        calculation="Weight times covariance-with-portfolio divided by portfolio variance, with volatility contribution annualized.",
        how_to_read="Use it to find positions that dominate risk even if their dollar weights look modest.",
        caution="Contribution estimates depend on the covariance lookback.",
        aliases=(
            "risk_contribution_pct",
            "annualized_vol_contribution",
            "marginal_risk_contribution",
        ),
    ),
    MetricExplainer(
        metric="HHI Concentration",
        category="Risk Engine",
        plain_english="Portfolio concentration score based on squared position weights.",
        calculation="Sum of squared weights across holdings.",
        how_to_read="Higher means fewer positions dominate the portfolio.",
        caution="Low HHI does not guarantee true diversification if positions share the same factor beta.",
        aliases=("max_concentration_hhi", "concentration_hhi"),
    ),
    MetricExplainer(
        metric="Vol-Adjusted Momentum Score",
        category="Signals",
        plain_english="Momentum score normalized by realized volatility for a tradable asset.",
        calculation="Lookback return with skip-period logic divided by realized volatility.",
        how_to_read="Positive is supportive, negative is adverse, near zero is mixed.",
        caution="Fast shocks can outrun vol-adjusted momentum trend signals.",
        aliases=("momentum_state_score", "momentum_state_label"),
    ),
    MetricExplainer(
        metric="Signal Inclusion Delta",
        category="Signals",
        plain_english="Backtest impact of adding a candidate signal or macro group.",
        calculation="Overlay metric minus base metric, such as delta CAGR or delta Sharpe.",
        how_to_read="Positive deltas with drawdown improvement are most interesting.",
        caution="A useful diagnostic signal may still be too noisy for direct sizing.",
        aliases=(
            "delta_cagr",
            "delta_sharpe",
            "delta_calmar",
            "max_drawdown_improvement",
            "active_day_rate",
        ),
    ),
    MetricExplainer(
        metric="Asset",
        category="Finance Glossary",
        plain_english="Something the portfolio can own or measure, such as an ETF, stock, bond fund, commodity fund, or cash-like instrument.",
        calculation="Not calculated; this is a portfolio building block.",
        how_to_read="When the dashboard says an asset is confirmed, defensive, or risk-on, it is talking about one tradable instrument or proxy.",
        caution="A ticker can represent a diversified fund, a single company, or a proxy series; inspect the asset type before comparing risk.",
        aliases=("asset", "holding", "instrument", "security"),
    ),
    MetricExplainer(
        metric="Ticker",
        category="Finance Glossary",
        plain_english="Short exchange symbol used to identify a tradable asset or market proxy.",
        calculation="Not calculated; it is the market identifier used for prices, returns, weights, and exposures.",
        how_to_read="Examples: SPY is an S&P 500 ETF, QQQ is a Nasdaq 100 ETF, and BIL is a short Treasury bill ETF.",
        caution="Ticker meaning can differ by exchange or data provider; confirm the underlying exposure before treating it as a pure signal.",
        aliases=("ticker", "symbol", "proxy_ticker"),
    ),
    MetricExplainer(
        metric="ETF",
        category="Finance Glossary",
        plain_english="Exchange-traded fund: a basket of securities that trades like a stock.",
        calculation="Not calculated; ETF returns come from the weighted returns of the assets it holds, minus fund costs and tracking differences.",
        how_to_read="ETF tickers such as SPY, QQQ, VEA, BIL, GLD, TLT, HYG, and SMH give trade-bot liquid exposure to broad themes.",
        caution="An ETF can be concentrated, leveraged, illiquid, or tax-inefficient even when it looks diversified.",
        aliases=("etf", "exchange traded fund", "fund"),
    ),
    MetricExplainer(
        metric="Equity",
        category="Finance Glossary",
        plain_english="Ownership exposure to companies, either through individual stocks or stock ETFs.",
        calculation="Equity return is the price change plus any dividends over the holding period.",
        how_to_read="Equities are usually treated as risk assets because they can compound strongly but can draw down sharply.",
        caution="Equity exposure can be broad, sector-specific, country-specific, or single-name; broad beta alone may hide concentration risk.",
        aliases=("equity", "equities", "stock", "stocks"),
    ),
    MetricExplainer(
        metric="Risk Asset",
        category="Finance Glossary",
        plain_english="A return-seeking asset expected to participate in market upside but also lose value in risk-off periods.",
        calculation="In trade-bot this is usually classified from configured asset groups and strategy target weights.",
        how_to_read="QQQ, SOXX, SMH, IWM, VEA, and many single stocks are usually risk assets.",
        caution="Risk assets can behave defensively for short windows, but they should not be relied on as cash protection.",
        aliases=("risk asset", "risk assets", "risk_asset_weight", "target_risk_asset_weight"),
    ),
    MetricExplainer(
        metric="Defensive Asset",
        category="Finance Glossary",
        plain_english="A lower-volatility or cash-like asset used to reduce portfolio risk.",
        calculation="In trade-bot this is usually a configured defensive group weight, currently dominated by BIL or cash-like exposure.",
        how_to_read="A higher defensive weight means the strategy is holding more capital away from risk assets.",
        caution="Defensive does not mean risk-free; cash-like funds still have rate, liquidity, and opportunity-cost risk.",
        aliases=("defensive asset", "defensive assets", "defensive", "defensive_weight", "target_defensive_weight"),
    ),
    MetricExplainer(
        metric="Cash Equivalent",
        category="Finance Glossary",
        plain_english="A very low-duration, cash-like holding used as a parking place for capital.",
        calculation="Return is usually short-term yield plus small price movement.",
        how_to_read="Trade-bot often uses BIL as the practical cash-equivalent sleeve when it wants to get defensive.",
        caution="Cash equivalents can still lose small amounts, lag inflation, or be unavailable in some account menus.",
        aliases=("cash equivalent", "cash-like", "cash", "money market", "parking capital"),
    ),
    MetricExplainer(
        metric="Treasury Bill",
        category="Finance Glossary",
        plain_english="Short-term U.S. government debt with low interest-rate sensitivity.",
        calculation="Return comes from short-term Treasury yield and small mark-to-market changes.",
        how_to_read="BIL is used as a Treasury bill ETF proxy for defensive/cash-like exposure.",
        caution="Treasury bills are low risk, not no risk; real returns can be negative after inflation and taxes.",
        aliases=("treasury bill", "t-bill", "tbill", "BIL", "short treasury"),
    ),
    MetricExplainer(
        metric="Bond",
        category="Finance Glossary",
        plain_english="Debt security whose value depends on interest rates, credit risk, maturity, and income yield.",
        calculation="Return combines coupon/yield income and price change from rate or spread movement.",
        how_to_read="Bond funds can be defensive or risky depending on duration and credit quality.",
        caution="Long-duration bonds can lose a lot when rates rise, and credit bonds can sell off with equities.",
        aliases=("bond", "bonds", "fixed income", "fixed-income"),
    ),
    MetricExplainer(
        metric="Duration",
        category="Finance Glossary",
        plain_english="Approximate sensitivity of a bond or bond fund to interest-rate changes.",
        calculation="A duration of 10 means a 1 percentage-point rate rise is roughly a 10 percent price headwind before convexity and income.",
        how_to_read="Higher duration usually means more upside when rates fall and more downside when rates rise.",
        caution="Duration is an approximation and can change as yields, maturities, and fund holdings change.",
        aliases=("duration", "duration_beta", "rate sensitivity", "interest-rate sensitivity", "TLT"),
    ),
    MetricExplainer(
        metric="Credit Risk",
        category="Finance Glossary",
        plain_english="Risk that borrowers become less able or less willing to repay debt.",
        calculation="Often inferred from high-yield bond performance, credit spreads, and credit-sensitive ETF returns.",
        how_to_read="Rising credit risk usually argues for more caution because funding conditions are tightening.",
        caution="Credit markets can lag equities or be distorted by liquidity and central-bank expectations.",
        aliases=("credit risk", "credit", "credit_beta", "credit stress", "private_credit"),
    ),
    MetricExplainer(
        metric="Credit Spread",
        category="Finance Glossary",
        plain_english="Extra yield investors demand to own risky debt instead of safer government debt.",
        calculation="Corporate or high-yield bond yield minus comparable Treasury yield.",
        how_to_read="Wider spreads usually mean more credit stress; tighter spreads usually mean easier risk appetite.",
        caution="ETF prices, yield spreads, and default risk can disagree over short windows.",
        aliases=("credit spread", "spreads", "high yield spread", "spread", "HYG"),
    ),
    MetricExplainer(
        metric="High Yield",
        category="Finance Glossary",
        plain_english="Lower-rated corporate debt that pays higher yield because default and liquidity risk are higher.",
        calculation="Return comes from coupon income, spread changes, defaults, and rate movement.",
        how_to_read="High-yield strength can confirm risk appetite; high-yield weakness can warn of stress.",
        caution="High yield is not a pure bond defensive asset; it often behaves partly like equity risk.",
        aliases=("high yield", "junk bonds", "hyg", "credit appetite"),
    ),
    MetricExplainer(
        metric="Commodity",
        category="Finance Glossary",
        plain_english="Exposure to raw materials such as energy, metals, or agriculture.",
        calculation="Returns come from spot price changes, futures roll yield, collateral yield, and ETF implementation.",
        how_to_read="Commodity exposure can hedge inflation or geopolitical supply shocks, but it can also be volatile.",
        caution="Commodity ETFs can differ materially from spot commodity moves because many use futures.",
        aliases=("commodity", "commodities", "DBC", "USO", "oil", "energy", "agriculture"),
    ),
    MetricExplainer(
        metric="Gold",
        category="Finance Glossary",
        plain_english="Precious-metal exposure often used as an inflation, real-rate, currency, or safe-haven proxy.",
        calculation="Gold ETF return is the gold price change minus fund costs and tracking differences.",
        how_to_read="Gold can diversify equity risk, but its drivers vary across regimes.",
        caution="Gold can fall during liquidity shocks or when real rates rise, so it is not a guaranteed hedge.",
        aliases=("gold", "GLD", "safe haven", "precious metals"),
    ),
    MetricExplainer(
        metric="Volatility",
        category="Finance Glossary",
        plain_english="How much returns move around over time.",
        calculation="Usually annualized standard deviation of daily returns.",
        how_to_read="Higher volatility means a wider range of normal outcomes and usually smaller position sizes for the same risk budget.",
        caution="Volatility measures typical movement, not the full crash tail.",
        aliases=("volatility", "vol", "annualized_volatility", "realized_volatility", "realized vol"),
    ),
    MetricExplainer(
        metric="Implied Volatility",
        category="Finance Glossary",
        plain_english="Option-market estimate of expected future volatility.",
        calculation="Backed out from option prices using an option-pricing model.",
        how_to_read="Rising implied volatility often means traders are paying more for protection or optionality.",
        caution="Implied volatility is not a forecast guarantee; it includes supply, demand, and risk-premium effects.",
        aliases=("implied volatility", "implied vol", "VIX", "VIXY", "option volatility"),
    ),
    MetricExplainer(
        metric="Value at Risk",
        category="Finance Glossary",
        plain_english="Loss threshold that should only be exceeded a specified share of the time under the historical/model sample.",
        calculation="For VaR 95, use the 5th percentile of returns and report the positive loss magnitude.",
        how_to_read="A 1 percent VaR 95 means the model estimates losses worse than 1 percent on about 5 percent of days.",
        caution="VaR says little about how bad losses can be after the threshold is breached; pair it with expected shortfall.",
        aliases=("value at risk", "var", "var_95", "value_at_risk"),
    ),
    MetricExplainer(
        metric="Tail Risk",
        category="Finance Glossary",
        plain_english="Risk of rare but large adverse outcomes.",
        calculation="Measured with tools such as expected shortfall, stress loss, drawdown, and severe-loss probabilities.",
        how_to_read="Tail risk matters when a portfolio looks fine in normal volatility but can fail badly in stress.",
        caution="Historical tails can understate future tails when markets enter regimes not present in the sample.",
        aliases=("tail risk", "left tail", "left-tail", "severe drawdown", "crash risk"),
    ),
    MetricExplainer(
        metric="Stress Test",
        category="Finance Glossary",
        plain_english="A what-if loss estimate under adverse market conditions.",
        calculation="Apply configured shocks or historical stress-window returns to current portfolio weights.",
        how_to_read="Use it to see whether the portfolio could survive plausible bad states before they happen.",
        caution="Stress tests are scenario choices, not exhaustive forecasts.",
        aliases=("stress test", "stress", "stress scenario", "stress loss"),
    ),
    MetricExplainer(
        metric="Scenario",
        category="Finance Glossary",
        plain_english="A possible future market state used for planning and sizing.",
        calculation="Trade-bot assigns scenario probabilities from current state, macro/news context, and configured scenario logic.",
        how_to_read="Scenario probabilities shape risk budgets and simulation ranges; they are not point forecasts.",
        caution="A scenario can be directionally useful and still have badly calibrated probability.",
        aliases=("scenario", "scenario lattice", "future state", "scenario probability", "probability"),
    ),
    MetricExplainer(
        metric="Risk-On",
        category="Finance Glossary",
        plain_english="Market environment where investors are generally willing to own growth, equity, credit, or cyclical risk.",
        calculation="In trade-bot this is a scenario/risk-bucket label inferred from market and scenario evidence.",
        how_to_read="Risk-on usually supports more exposure to return-seeking assets.",
        caution="Risk-on can be fragile if leadership is narrow, valuations are stretched, or credit/breadth confirmation is weak.",
        aliases=("risk-on", "risk_on", "broad risk-on", "risk appetite"),
    ),
    MetricExplainer(
        metric="Risk-Off",
        category="Finance Glossary",
        plain_english="Market environment where investors prefer capital preservation and reduce risky exposure.",
        calculation="In trade-bot this is a scenario/risk-bucket label and probability used in sizing rules.",
        how_to_read="Higher risk-off probability pushes the system toward smaller risk budgets and more defensive weight.",
        caution="Risk-off warnings can be false alarms, especially during short-lived pullbacks in strong trends.",
        aliases=("risk-off", "risk_off", "risk off", "capital preservation"),
    ),
    MetricExplainer(
        metric="Transition Regime",
        category="Finance Glossary",
        plain_english="Mixed market state where leadership, breadth, credit, or volatility signals are changing but direction is not settled.",
        calculation="Scenario probabilities and current-state signals classify some outcomes as transition buckets.",
        how_to_read="Transition usually argues for caution, smaller size, or waiting for confirmation.",
        caution="Transitions can resolve into either risk-on continuation or risk-off drawdown.",
        aliases=("transition regime", "transition", "regime transition", "choppy factor rotation"),
    ),
    MetricExplainer(
        metric="Fragile Risk-On",
        category="Finance Glossary",
        plain_english="Upside environment where markets can keep rising, but participation is narrow or conditions look unstable.",
        calculation="Scenario bucket used when upside exists alongside fragility such as narrow leadership, AI concentration, or volatility pressure.",
        how_to_read="This supports some upside participation but warns against treating the regime like broad healthy risk-on.",
        caution="Fragile rallies can persist longer than expected or break quickly when leadership fails.",
        aliases=("fragile risk-on", "risk_on_fragile", "fragile upside", "narrow melt-up", "narrow AI-led melt-up"),
    ),
    MetricExplainer(
        metric="Factor",
        category="Finance Glossary",
        plain_english="A common return driver shared by many assets, such as broad market, growth, value, AI/semiconductors, credit, rates, commodities, or gold.",
        calculation="Usually measured through proxy ETF returns and regression-style exposure estimates.",
        how_to_read="Factors explain why different tickers may actually be making the same bet.",
        caution="Factor labels are approximations; missing factors can make residual behavior look more unique than it is.",
        aliases=("factor", "factors", "factor model", "risk factor"),
    ),
    MetricExplainer(
        metric="Factor Exposure",
        category="Finance Glossary",
        plain_english="How sensitive a strategy or portfolio is to a shared return driver.",
        calculation="Usually estimated as beta to a proxy factor over a rolling or full-history window.",
        how_to_read="High exposure means that factor is likely doing a lot of work in the strategy.",
        caution="Exposure can change quickly after correlations or holdings shift.",
        aliases=("factor exposure", "factor_exposures", "exposure", "absolute_beta"),
    ),
    MetricExplainer(
        metric="Proxy",
        category="Finance Glossary",
        plain_english="A tradable or measurable stand-in used to approximate a larger market theme.",
        calculation="Not calculated; the proxy is selected by configuration or model design.",
        how_to_read="Examples: SPY proxies broad U.S. equities, QQQ proxies Nasdaq growth, SMH proxies semiconductors, and HYG proxies credit appetite.",
        caution="A proxy is imperfect. It can add sector, duration, liquidity, or issuer-specific behavior beyond the intended theme.",
        aliases=("proxy", "proxy ticker", "market proxy", "factor proxy"),
    ),
    MetricExplainer(
        metric="Market Beta",
        category="Finance Glossary",
        plain_english="Sensitivity to broad equity-market movement.",
        calculation="Regression-style exposure to a market proxy such as SPY.",
        how_to_read="A market beta of 0.50 means the portfolio has historically moved about half as much as SPY for broad-market moves.",
        caution="Market beta is linear and backward-looking; it can understate crash behavior when correlations jump.",
        aliases=("market beta", "market_beta", "SPY beta", "broad equity beta"),
    ),
    MetricExplainer(
        metric="Beta",
        category="Finance Glossary",
        plain_english="Sensitivity of an asset or portfolio to a reference market, factor, or proxy.",
        calculation="Typically estimated by regressing asset returns against the reference returns over a lookback window.",
        how_to_read="Beta near 1 moves like the reference; beta below 1 is less sensitive; beta above 1 is more sensitive.",
        caution="Beta is historical and can change when market structure, volatility, or correlations change.",
        aliases=("beta", "factor beta", "rolling beta"),
    ),
    MetricExplainer(
        metric="Correlation",
        category="Finance Glossary",
        plain_english="How closely two return series move together.",
        calculation="Statistical correlation ranges from -1 to +1.",
        how_to_read="Positive means they tend to move together; negative means they tend to move opposite; near zero means weak linear relationship.",
        caution="Correlation can rise during stress, reducing diversification when it is needed most.",
        aliases=("correlation", "average correlation", "pairwise correlation"),
    ),
    MetricExplainer(
        metric="Concentration",
        category="Finance Glossary",
        plain_english="How much of the portfolio depends on a small number of positions or one common theme.",
        calculation="Measured through position weights, HHI, max single-asset weight, and factor exposures.",
        how_to_read="High concentration can boost returns when the theme works but can create sharp losses if it fails.",
        caution="A portfolio can look diversified by ticker count while still being concentrated in one factor like AI/growth.",
        aliases=("concentration", "concentrated", "max_single_asset", "single asset cap"),
    ),
    MetricExplainer(
        metric="Portfolio Weight",
        category="Finance Glossary",
        plain_english="Percent of the portfolio allocated to a holding or group.",
        calculation="Holding value divided by total portfolio value.",
        how_to_read="A 25 percent weight means one quarter of the portfolio is allocated to that asset or group.",
        caution="Weight is not the same as risk contribution; a low-weight volatile asset can still dominate risk.",
        aliases=("portfolio weight", "weight", "target_weight", "current_weight", "risk_adjusted_weight"),
    ),
    MetricExplainer(
        metric="Sleeve",
        category="Finance Glossary",
        plain_english="A named portion of the portfolio reserved for a strategy, theme, account, or asset group.",
        calculation="Sleeve size is usually configured as a percent of account value or policy maximum.",
        how_to_read="Sleeves help separate operating decisions, such as a paper strategy sleeve versus core retirement holdings.",
        caution="Sleeve limits are governance choices, not proof that the sleeve should be fully used.",
        aliases=("sleeve", "max sleeve", "strategy sleeve", "account sleeve"),
    ),
    MetricExplainer(
        metric="Rebalance",
        category="Finance Glossary",
        plain_english="Trades that move current holdings back toward target weights.",
        calculation="Target weight minus current weight, translated into dollars or shares.",
        how_to_read="Large rebalance amounts deserve more review, especially in taxable or illiquid accounts.",
        caution="Frequent rebalancing can increase costs, taxes, and behavioral churn.",
        aliases=("rebalance", "rebalancing", "target drift", "drift", "book alignment"),
    ),
    MetricExplainer(
        metric="Benchmark",
        category="Finance Glossary",
        plain_english="Reference portfolio used to judge whether a strategy is adding value.",
        calculation="Compare strategy return, drawdown, volatility, or wealth to the benchmark over the same window.",
        how_to_read="For high-growth tech-heavy strategies, QQQ plus BIL/cash can be a more relevant hurdle than SPY alone.",
        caution="Choosing an easy benchmark can make a weak strategy look good; choose the hurdle that matches the strategy's opportunity set.",
        aliases=("benchmark", "reference", "reference portfolio", "hurdle", "buy_hold_qqq", "buy_hold_spy"),
    ),
    MetricExplainer(
        metric="Excess Return",
        category="Finance Glossary",
        plain_english="Return above or below a benchmark over the same period.",
        calculation="Strategy return minus benchmark return.",
        how_to_read="Positive excess return means the strategy beat the selected benchmark for that window.",
        caution="Excess return depends heavily on benchmark choice and can be negative even when absolute return is positive.",
        aliases=("excess return", "benchmark excess", "excess_return", "strategy vs benchmark"),
    ),
    MetricExplainer(
        metric="Alpha",
        category="Finance Glossary",
        plain_english="Return not explained by broad market or factor exposures.",
        calculation="Often estimated as the regression intercept or residual return after factor model exposure is removed.",
        how_to_read="True alpha would mean the strategy adds value beyond simple factor bets.",
        caution="Apparent alpha can be overfit, missing-factor exposure, luck, or data leakage.",
        aliases=("alpha", "residual return", "unexplained return"),
    ),
    MetricExplainer(
        metric="Tracking Error",
        category="Finance Glossary",
        plain_english="How much a strategy's returns differ from a benchmark's returns.",
        calculation="Annualized standard deviation of strategy return minus benchmark return.",
        how_to_read="High tracking error means the strategy can look very different from the benchmark for long stretches.",
        caution="Low tracking error does not guarantee good returns, and high tracking error may be acceptable for a deliberately different strategy.",
        aliases=("tracking error", "active risk", "benchmark volatility"),
    ),
    MetricExplainer(
        metric="Return Contribution",
        category="Finance Glossary",
        plain_english="How much a holding, group, or factor added to portfolio return.",
        calculation="Position weight times asset return, or fitted factor contribution in an attribution model.",
        how_to_read="Use it to see what actually drove gains or losses instead of relying on headline weights.",
        caution="Contribution is historical and can confuse exposure with skill when one theme dominates the sample.",
        aliases=("return contribution", "contribution", "factor contribution", "return_contribution"),
    ),
    MetricExplainer(
        metric="High-Water Mark",
        category="Finance Glossary",
        plain_english="Highest previous value of an equity curve or account balance.",
        calculation="Running maximum of portfolio value through time.",
        how_to_read="Drawdown is measured from the high-water mark to the current or trough value.",
        caution="A strategy can be below its high-water mark for a long time even if its current drawdown is not severe.",
        aliases=("high-water mark", "high water mark", "prior peak", "equity peak"),
    ),
    MetricExplainer(
        metric="Long-Only",
        category="Finance Glossary",
        plain_english="Portfolio design that owns assets but does not short them.",
        calculation="Weights are constrained to be zero or positive, usually summing to the configured invested amount.",
        how_to_read="Trade-bot is designed around long-only human-run retirement-account workflows.",
        caution="Long-only systems reduce risk by moving to defensive assets rather than profiting directly from short exposure.",
        aliases=("long-only", "long only", "no shorts", "shorting"),
    ),
    MetricExplainer(
        metric="Liquidity",
        category="Finance Glossary",
        plain_english="How easily an asset can be bought or sold without meaningfully moving its price.",
        calculation="Usually assessed from volume, bid-ask spread, market depth, and fund structure.",
        how_to_read="Higher liquidity makes execution and rebalancing easier.",
        caution="Liquidity can disappear during stress, especially in niche ETFs, credit, or single-name positions.",
        aliases=("liquidity", "liquid", "bid ask", "bid-ask spread", "volume"),
    ),
    MetricExplainer(
        metric="Command Center",
        category="Workflow",
        plain_english="Operating overview for today's action, book alignment, and trade-decision summary.",
        calculation="Renders the latest snapshot's action headline, operating brief, book alignment, and current state tables.",
        how_to_read="Start here when asking what needs attention today.",
        caution="Detailed research, simulations, and monitoring live in their own workbench sections.",
        aliases=("command center", "action headline", "operating brief", "decision brief", "current state"),
    ),
    MetricExplainer(
        metric="Risk & Scenarios",
        category="Workflow",
        plain_english="Workbench for current market risk, scenario probabilities, and how they have evolved over time.",
        calculation="Combines the current risk score, confirmation matrix, scenario lattice, and stored scenario-history snapshots.",
        how_to_read="Use this to understand whether risk is rising, falling, or changing composition.",
        caution="Scenario probabilities drive sizing only through validated risk rules; not every scenario note is a trade signal.",
        aliases=("risk scenarios", "risk and scenarios", "scenario history", "regime probabilities"),
    ),
    MetricExplainer(
        metric="Research Lab",
        category="Workflow",
        plain_english="Cross-experiment research workbench for ranking, curating, and inspecting strategy candidates.",
        calculation="Reads experiment scorecards, validation diagnostics, curated shelves, family maps, and candidate detail artifacts.",
        how_to_read="Use the upper area for aggregate experiment comparisons and the lower area for one selected candidate.",
        caution="Research ranking is not the same as live approval; candidates still need paper and launch review.",
        aliases=("research lab", "experiment monitor", "candidate details", "curated shelf", "leaderboard"),
    ),
    MetricExplainer(
        metric="Simulation Lab",
        category="Workflow",
        plain_english="Forward-looking planning workbench for deterministic, bootstrap, and regime-conditioned simulation results.",
        calculation="Uses configured account assumptions, historical return libraries, scenario probabilities, and reference overlays.",
        how_to_read="Use it to compare possible future wealth, drawdown, and reference outcomes.",
        caution="Simulation ranges are planning distributions, not point forecasts.",
        aliases=("simulation lab", "future-state map", "strategy simulations", "simulation interpretability"),
    ),
    MetricExplainer(
        metric="Launch Lab",
        category="Workflow",
        plain_english="Entry-timing workbench for deciding whether to start or scale a strategy now.",
        calculation="Combines current launch diagnostics with historical launch-window tests and ramp protocols.",
        how_to_read="Use it before putting new paper, pseudo-live, or live capital into a strategy.",
        caution="Once a sleeve is already running, daily target drift belongs in Book Alignment and Forward Test.",
        aliases=("launch lab", "launch gate", "entry backtest", "ramp plan", "launching vs operating"),
    ),
    MetricExplainer(
        metric="Monitoring",
        category="Workflow",
        plain_english="Champion/challenger forward evidence area for paper and reference strategies.",
        calculation="Reads monitoring windows, daily valuations, benchmark comparisons, and warehouse health tables.",
        how_to_read="Use it to see whether monitored strategies are behaving like their backtests after adoption.",
        caution="Short forward windows are evidence gathering, not enough by themselves to scale live capital.",
        aliases=("monitoring", "champion challenger", "strategy registry", "warehouse health", "active windows"),
    ),
    MetricExplainer(
        metric="News & Macro",
        category="Workflow",
        plain_english="Context workbench for macro series, news intake, events, and watch-only narrative diagnostics.",
        calculation="Summarizes loaded macro data, active events, news-derived context, and source coverage.",
        how_to_read="Use this to audit what the system is watching and whether a context item is validated or explainer-only.",
        caution="News and narrative context should not be treated as a trade driver unless ablation tests support it.",
        aliases=("news macro", "news and macro", "daily market brief", "latest news", "events"),
    ),
    MetricExplainer(
        metric="Performance",
        category="Workflow",
        plain_english="Historical performance workbench for selected strategies and references.",
        calculation="Shows windowed returns, drawdowns, growth of one dollar, and comparison metrics.",
        how_to_read="Use it to compare historical behavior across custom windows and benchmarks.",
        caution="Past performance can be regime-specific; use it with Research Lab validation and Simulation Lab ranges.",
        aliases=("performance", "growth of $1", "custom window", "historical performance"),
    ),
    MetricExplainer(
        metric="Forward Test",
        category="Workflow",
        plain_english="Execution and record-keeping area for paper or live tickets, logs, and forward allocation history.",
        calculation="Uses locked recommendation tickets, execution logs, current books, valuations, and forward allocation records.",
        how_to_read="Use it to log what was actually done and compare the running book with the intended target path.",
        caution="Forward Test records are only as accurate as the tickets, executions, and prices entered or refreshed.",
        aliases=("forward test", "ticket logging", "execution log", "forward allocation history", "paper trades"),
    ),
)


def metric_help(metric_name: str) -> str | None:
    explainer = metric_detail(metric_name)
    if explainer is None:
        return None
    return (
        f"{explainer.plain_english}\n\n"
        f"How to read: {explainer.how_to_read}\n\n"
        f"Watch out: {explainer.caution}"
    )


def metric_detail(metric_name: str) -> MetricExplainer | None:
    return _EXPLAINER_BY_KEY.get(_normalize_key(metric_name))


def metric_categories() -> tuple[str, ...]:
    return tuple(dict.fromkeys(explainer.category for explainer in METRIC_EXPLAINERS))


def metric_guide_frame(
    *,
    category: str | None = None,
    search: str = "",
) -> pd.DataFrame:
    rows = [
        {
            "metric": explainer.metric,
            "category": explainer.category,
            "plain_english": explainer.plain_english,
            "calculation": explainer.calculation,
            "how_to_read": explainer.how_to_read,
            "caution": explainer.caution,
            "aliases": ", ".join(explainer.aliases),
        }
        for explainer in METRIC_EXPLAINERS
    ]
    frame = pd.DataFrame(rows)
    if category:
        frame = frame[frame["category"] == category]
    query = search.strip().lower()
    if query:
        haystack = frame.astype(str).agg(" ".join, axis=1).str.lower()
        normalized_query = _normalize_key(query)
        normalized_haystack = haystack.map(_normalize_key)
        frame = frame[
            haystack.str.contains(re.escape(query), na=False)
            | normalized_haystack.str.contains(re.escape(normalized_query), na=False)
        ]
    return frame.reset_index(drop=True)


def _build_explainer_lookup() -> dict[str, MetricExplainer]:
    lookup: dict[str, MetricExplainer] = {}
    for explainer in METRIC_EXPLAINERS:
        for key in (explainer.metric, *explainer.aliases):
            lookup[_normalize_key(key)] = explainer
    return lookup


def _normalize_key(value: str) -> str:
    normalized = value.strip().lower()
    normalized = normalized.replace("$", " dollar ")
    normalized = re.sub(r"[^a-z0-9]+", "_", normalized)
    return normalized.strip("_")


_EXPLAINER_BY_KEY = _build_explainer_lookup()
